### PR TITLE
Updated for Atom 1.0

### PR DESCRIPTION
**Pull request by RichardSlater**
I have updated this package to work with the new API in Atom 1.0.  The version currently published on atom.io does not work in Atom 1.6 or Atom 1.7.

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
thanks

**Comment by RichardSlater** [comment]
your welcome, this package has already saved me the time it took to get it working in Atom 1.7.

**Comment by MasseGuillaume** [comment]
hehe, I dont understand why it's not built-in.

**Comment by RichardSlater** [comment]
Any chance you could do an `apm publish minor` on this package?

**Comment by MasseGuillaume** [comment]
done 0.8.0

**Comment by RichardSlater** [comment]
Again - Thank You

**Pull request merged**
